### PR TITLE
Breaking: Add support for laravel 11, test on php 8.3, remove old laravel versions

### PR DESCRIPTION
**Pull request by steache**

### CODE REVIEW

**Comment by ssi-anik** [comment]
@steache I am sorry for replying this late.

I was thinking of dropping L**6,7,8,9** and only keeping L**10** and onwards with PHP **^8.1**

Can you make those changes on the composer as well as the workflow yml files?

TIA.

---

EDIT: also in the readme, in case someone wants to use the removed versions, they get forwarded to the older versions.

**Comment by steache** [comment]
- @ssi-anik  so something like this?
 - I've removed old versions
 - I did not get the part with readme. :)
 - I've changed the title, becase this will be breaking change, not fix.

**Comment by ssi-anik** [comment]
@steache thanks mate.

Those Laravel versions are already deprecated and there is no code-related change so far. So I dropped all those previous versions. And, I am going to make a new tag so the upcoming changes (if any) should go under new tags.

Finally, thanks for the help. 🙏

**Comment by ssi-anik** [comment]
@steache I have added new tag [`v2.0`](https://packagist.org/packages/anik/laravel-amqp#v2.0).

**Pull request merged**
