### PR TITLE
Laravel 10

### PR DESCRIPTION
**Pull request by stefnats**

### CODE REVIEW

**Comment by ssi-anik** [comment]
Thanks for the PR. As the lazy SSL connection

**Comment by ssi-anik** [comment]
Thanks for the PR. As the default lazy ssl connection is causing the tests to fail, I will try to fix that first and get back here.

**Comment by ssi-anik** [comment]
Blocked by php-amqplib/php-amqplib/issues/1076

**Comment by stefnats** [comment]
FYI, php-amqplib has been released v3.5.2

**Comment by ssi-anik** [comment]
@stefnats yes, I have tagged my core repo and made changes here too. can you pull the latest changes and push them to your branch to run the checks again?

**Comment by ssi-anik** [comment]
@stefnats thanks for the PR. I forgot to check the orchestra/testbench's update in the `composer.json`. Updated and tagged with `v1.4`

**Pull request merged**
